# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71074b8e62de0db07acd1c82375affa0ce74041d7e2a53839fcb648cd72cc8c79b39dd48fbb81630ea974bd84a98278054e72e03cbed138966a1c75c6c5d8c3e

test:
  secret_key_base: 77c0671dcb739e437861cc87d0f1353de6d44635e20facc16cfe5e6084b901f0cb97269a6c08b18add952997e6a7d4773e5fdb263bd47196e46c85c5b31048fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
